[alias]
b = "build"
c = "check"
f = "fmt"
r = "run"
t = "test"
br = "build --release"
rq = "run -q"
rr = "run --release"

[build]
jobs = 6
rustflags = ["-C", "target-cpu=native"]

[net]
git-fetch-with-cli = true

[profile.release]
lto = true

[profile.bench]
lto = true

[source.crates-io]
replace-with = "ustc"

[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"

[source.nju]
registry = "https://mirror.nju.edu.cn/git/crates.io-index.git"

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[source.sjtu]
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/"
