[alias]
f = "fmt"
r = "run"
t = "test"
b = "build"
c = "clippy"
rq = "run -q"
rr = "run --release"
br = "build --release"

[net]
git-fetch-with-cli = true

[profile.release]
lto = true
strip = true
codegen-units = 1
incremental = false

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[source.crates-io]
replace-with = "rsproxy"

[source.rsproxy]
registry = "sparse+https://rsproxy.cn/index/"

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[source.sjtu]
registry = "sparse+https://mirrors.sjtug.sjtu.edu.cn/crates.io-index/"

[source.tuna]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"
