[alias]
f = "fmt"
r = "run"
t = "test"
c = "check"
b = "build"
rq = "run -q"
rr = "run --release"
br = "build --release"

[build]
jobs = 6
rustflags = ["-C", "target-cpu=native"]

[net]
git-fetch-with-cli = true

[profile.dev]
incremental = true
codegen-units = 64

[profile.release]
lto = true
strip = true
codegen-units = 1
incremental = false

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[source.crates-io]
replace-with = "rsproxy"

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"

[source.nju]
registry = "https://mirror.nju.edu.cn/git/crates.io-index.git"

[source.sjtu]
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/"

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
