[alias]
b = "build"
c = "check"
r = "run"
t = "test"
br = "build --release"
rq = "run -q"
rr = "run --release"

[build]
rustflags = ["-C", "target-cpu=native"]
incremental = true

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 8
incremental = true

[profile.bench]
lto = true
opt-level = 'z'
codegen-units = 8
incremental = true

[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = "ustc"

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"

[source.sjtu]
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index"
