theme = "nord"

[editor]
idle-timeout = 0
true-color = true
color-modes	= true
popup-border = "none"
bufferline = "multiple"
line-number = "relative"
auto-completion = true
# completion-timeout = 100
completion-trigger-len = 1

[editor.statusline]
left = ["mode", "file-name"]
center = []
right = ["spinner", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.lsp]
display-messages = false
