#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width                  3
bspc config window_gap                    5
bspc config split_ratio                   0.50
bspc config single_monocle                false
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true

bspc config normal_border_color           "#4c566a"
bspc config active_border_color           "#1e1e1e"
bspc config focused_border_color          "#3c3836"
bspc config presel_feedback_color         "#3c3836"
