[client]
no-beep
port=3306
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4

[mysqld]
basedir = C:\Program Files\mysql
datadir = C:\Program Files\mysql\data
max_connections=200
default-storage-engine=INNODB
character-set-client-handshake=FALSE
skip-character-set-client-handshake
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci