title   Arch Linux (fallback)
linux   /vmlinuz-linux
initrd  /amd-ucode.img
initrd  /initramfs-linux-fallback.img
options root=PARTUUID= rw quiet splash
options acpi_backlight=vendor systemd.restore_state=0 usbcore.autosuspend=-1
