CompileFlags:
  Add: [-Wall, -Wextra]

If:
  PathMatch: /usr/include/.*
Diagnostics:
  Suppress: "*"

Index:
  Background: Build
  StandardLibrary: Yes

Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: [bugprone*, portability*, performance*]

InlayHints:
  Enabled: No
