CompileFlags:
  Add: [-Wall]

Index:
  Background: Skip

Diagnostics:
  ClangTidy:
    Add: [
        bugprone-*,
        modernize-*,
        readability-*,
        performance-*,
      ]
    CheckOptions:
