CompileFlags:
  Add: [-Wall, -Wextra]

Index:
  Background: Skip

Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: [bugprone-*, modernize-*, readability-*, performance-*]
    CheckOptions:
