CompileFlags:
  Add: [-Wall, -Wextra]

Index:
  Background: Build

Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: [bugprone*, portability*, performance*, modernize*]
    Remove: modernize-use-trailing-return-type
